version: '3.8'

services:
  web_indices:
    build:
      context: ./indices
    ports:
    - 8000:5000
    volumes:
    - ./indices:/indices
    depends_on:
    - mysqldb

  mysqldb:
    build:
      context: ./mysql
    ports:
    - 3307:3306
    environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
    - ./mysql/sqls:/docker-entrypoint-initdb.d